// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBets.Data;

#nullable disable

namespace SmartBets.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331143110_Stage2MatchCenter")]
    partial class Stage2MatchCenter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBets.Entities.Bookmaker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiBookmakerId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_bookmaker_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ApiBookmakerId")
                        .IsUnique();

                    b.ToTable("bookmakers", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("FlagUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("flag_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Fixture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiFixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_fixture_id");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<long>("AwayTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("away_team_id");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<long>("HomeTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("home_team_id");

                    b.Property<DateTime>("KickoffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kickoff_at");

                    b.Property<DateTime?>("LastEventSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_event_synced_at_utc");

                    b.Property<DateTime?>("LastLineupsSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_lineups_synced_at_utc");

                    b.Property<DateTime?>("LastPlayerStatisticsSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_player_statistics_synced_at_utc");

                    b.Property<DateTime?>("LastStatisticsSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_statistics_synced_at_utc");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_id");

                    b.Property<int>("PostFinishMatchCenterSyncCount")
                        .HasColumnType("integer")
                        .HasColumnName("post_finish_match_center_sync_count");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ApiFixtureId")
                        .IsUnique();

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("KickoffAt");

                    b.HasIndex("LeagueId");

                    b.ToTable("fixtures", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.FixtureEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("ApiTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_team_id");

                    b.Property<long?>("AssistApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("assist_api_id");

                    b.Property<string>("AssistName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assist_name");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("comments");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("detail");

                    b.Property<int?>("Elapsed")
                        .HasColumnType("integer")
                        .HasColumnName("elapsed");

                    b.Property<int?>("Extra")
                        .HasColumnType("integer")
                        .HasColumnName("extra");

                    b.Property<long>("FixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("fixture_id");

                    b.Property<long?>("PlayerApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_api_id");

                    b.Property<string>("PlayerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("player_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at_utc");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("team_logo_url");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FixtureId", "SortOrder");

                    b.ToTable("fixture_events", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.FixtureLineup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_team_id");

                    b.Property<long?>("CoachApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("coach_api_id");

                    b.Property<string>("CoachName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("coach_name");

                    b.Property<string>("CoachPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("coach_photo_url");

                    b.Property<long>("FixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("fixture_id");

                    b.Property<string>("Formation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formation");

                    b.Property<bool>("IsStarting")
                        .HasColumnType("boolean")
                        .HasColumnName("is_starting");

                    b.Property<long?>("PlayerApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_api_id");

                    b.Property<string>("PlayerGrid")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("player_grid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("player_name");

                    b.Property<int?>("PlayerNumber")
                        .HasColumnType("integer")
                        .HasColumnName("player_number");

                    b.Property<string>("PlayerPosition")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("player_position");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at_utc");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("team_logo_url");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team_name");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FixtureId", "ApiTeamId", "IsStarting", "SortOrder");

                    b.ToTable("fixture_lineups", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.FixturePlayerStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_team_id");

                    b.Property<int?>("CardsRed")
                        .HasColumnType("integer")
                        .HasColumnName("cards_red");

                    b.Property<int?>("CardsYellow")
                        .HasColumnType("integer")
                        .HasColumnName("cards_yellow");

                    b.Property<int?>("DribblesAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("dribbles_attempts");

                    b.Property<int?>("DribblesPast")
                        .HasColumnType("integer")
                        .HasColumnName("dribbles_past");

                    b.Property<int?>("DribblesSuccess")
                        .HasColumnType("integer")
                        .HasColumnName("dribbles_success");

                    b.Property<int?>("DuelsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("duels_total");

                    b.Property<int?>("DuelsWon")
                        .HasColumnType("integer")
                        .HasColumnName("duels_won");

                    b.Property<long>("FixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("fixture_id");

                    b.Property<int?>("FoulsCommitted")
                        .HasColumnType("integer")
                        .HasColumnName("fouls_committed");

                    b.Property<int?>("FoulsDrawn")
                        .HasColumnType("integer")
                        .HasColumnName("fouls_drawn");

                    b.Property<int?>("GoalsAssists")
                        .HasColumnType("integer")
                        .HasColumnName("goals_assists");

                    b.Property<int?>("GoalsConceded")
                        .HasColumnType("integer")
                        .HasColumnName("goals_conceded");

                    b.Property<int?>("GoalsSaves")
                        .HasColumnType("integer")
                        .HasColumnName("goals_saves");

                    b.Property<int?>("GoalsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("goals_total");

                    b.Property<bool>("IsCaptain")
                        .HasColumnType("boolean")
                        .HasColumnName("is_captain");

                    b.Property<bool>("IsSubstitute")
                        .HasColumnType("boolean")
                        .HasColumnName("is_substitute");

                    b.Property<int?>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<int?>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int?>("Offsides")
                        .HasColumnType("integer")
                        .HasColumnName("offsides");

                    b.Property<string>("PassesAccuracy")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("passes_accuracy");

                    b.Property<int?>("PassesKey")
                        .HasColumnType("integer")
                        .HasColumnName("passes_key");

                    b.Property<int?>("PassesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("passes_total");

                    b.Property<int?>("PenaltyCommitted")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_committed");

                    b.Property<int?>("PenaltyMissed")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_missed");

                    b.Property<int?>("PenaltySaved")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_saved");

                    b.Property<int?>("PenaltyScored")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_scored");

                    b.Property<int?>("PenaltyWon")
                        .HasColumnType("integer")
                        .HasColumnName("penalty_won");

                    b.Property<long>("PlayerApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_api_id");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("player_name");

                    b.Property<string>("PlayerPhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("player_photo_url");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("position");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("rating");

                    b.Property<int?>("ShotsOn")
                        .HasColumnType("integer")
                        .HasColumnName("shots_on");

                    b.Property<int?>("ShotsTotal")
                        .HasColumnType("integer")
                        .HasColumnName("shots_total");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at_utc");

                    b.Property<int?>("TacklesBlocks")
                        .HasColumnType("integer")
                        .HasColumnName("tackles_blocks");

                    b.Property<int?>("TacklesInterceptions")
                        .HasColumnType("integer")
                        .HasColumnName("tackles_interceptions");

                    b.Property<int?>("TacklesTotal")
                        .HasColumnType("integer")
                        .HasColumnName("tackles_total");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("team_logo_url");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team_name");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FixtureId", "ApiTeamId", "PlayerApiId");

                    b.ToTable("fixture_player_statistics", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.FixtureStatistic", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_team_id");

                    b.Property<long>("FixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("fixture_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("synced_at_utc");

                    b.Property<long?>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<string>("TeamLogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("team_logo_url");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("team_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("type");

                    b.Property<string>("Value")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FixtureId", "ApiTeamId", "SortOrder");

                    b.ToTable("fixture_statistics", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.League", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiLeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_league_id");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ApiLeagueId", "Season")
                        .IsUnique();

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.LeagueSeasonCoverage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasFixtureEvents")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fixture_events");

                    b.Property<bool>("HasFixtureStatistics")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fixture_statistics");

                    b.Property<bool>("HasFixtures")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fixtures");

                    b.Property<bool>("HasInjuries")
                        .HasColumnType("boolean")
                        .HasColumnName("has_injuries");

                    b.Property<bool>("HasLineups")
                        .HasColumnType("boolean")
                        .HasColumnName("has_lineups");

                    b.Property<bool>("HasOdds")
                        .HasColumnType("boolean")
                        .HasColumnName("has_odds");

                    b.Property<bool>("HasPlayerStatistics")
                        .HasColumnType("boolean")
                        .HasColumnName("has_player_statistics");

                    b.Property<bool>("HasPlayers")
                        .HasColumnType("boolean")
                        .HasColumnName("has_players");

                    b.Property<bool>("HasPredictions")
                        .HasColumnType("boolean")
                        .HasColumnName("has_predictions");

                    b.Property<bool>("HasStandings")
                        .HasColumnType("boolean")
                        .HasColumnName("has_standings");

                    b.Property<bool>("HasTopAssists")
                        .HasColumnType("boolean")
                        .HasColumnName("has_top_assists");

                    b.Property<bool>("HasTopCards")
                        .HasColumnType("boolean")
                        .HasColumnName("has_top_cards");

                    b.Property<bool>("HasTopScorers")
                        .HasColumnType("boolean")
                        .HasColumnName("has_top_scorers");

                    b.Property<long>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Season");

                    b.HasIndex("LeagueApiId", "Season")
                        .IsUnique();

                    b.ToTable("league_season_coverages", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.PreMatchOdd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AwayOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("away_odd");

                    b.Property<long>("BookmakerId")
                        .HasColumnType("bigint")
                        .HasColumnName("bookmaker_id");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<decimal?>("DrawOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("draw_odd");

                    b.Property<long>("FixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("fixture_id");

                    b.Property<decimal?>("HomeOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("home_odd");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("market_name");

                    b.HasKey("Id");

                    b.HasIndex("BookmakerId");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FixtureId", "BookmakerId", "MarketName", "CollectedAt");

                    b.ToTable("pre_match_odds", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Standing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("Draw")
                        .HasColumnType("integer")
                        .HasColumnName("draw");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("form");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer")
                        .HasColumnName("goals_against");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("integer")
                        .HasColumnName("goals_diff");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer")
                        .HasColumnName("goals_for");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_id");

                    b.Property<int>("Lose")
                        .HasColumnType("integer")
                        .HasColumnName("lose");

                    b.Property<int>("Played")
                        .HasColumnType("integer")
                        .HasColumnName("played");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<int>("Win")
                        .HasColumnType("integer")
                        .HasColumnName("win");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("Rank");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "Season", "TeamId")
                        .IsUnique();

                    b.ToTable("standings", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.SupportedLeague", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.HasIndex("LeagueApiId", "Season")
                        .IsUnique();

                    b.ToTable("supported_leagues", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.SyncError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<long?>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<int?>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityType", "LeagueApiId", "Season");

                    b.ToTable("sync_errors", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<long?>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<int?>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "LeagueApiId", "Season")
                        .IsUnique();

                    b.ToTable("sync_states", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_team_id");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ApiTeamId")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Fixture", b =>
                {
                    b.HasOne("SmartBets.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.League", "League")
                        .WithMany("Fixtures")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("SmartBets.Entities.FixtureEvent", b =>
                {
                    b.HasOne("SmartBets.Entities.Fixture", "Fixture")
                        .WithMany("Events")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SmartBets.Entities.FixtureLineup", b =>
                {
                    b.HasOne("SmartBets.Entities.Fixture", "Fixture")
                        .WithMany("Lineups")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SmartBets.Entities.FixturePlayerStatistic", b =>
                {
                    b.HasOne("SmartBets.Entities.Fixture", "Fixture")
                        .WithMany("PlayerStatistics")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SmartBets.Entities.FixtureStatistic", b =>
                {
                    b.HasOne("SmartBets.Entities.Fixture", "Fixture")
                        .WithMany("Statistics")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SmartBets.Entities.League", b =>
                {
                    b.HasOne("SmartBets.Entities.Country", "Country")
                        .WithMany("Leagues")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SmartBets.Entities.PreMatchOdd", b =>
                {
                    b.HasOne("SmartBets.Entities.Bookmaker", "Bookmaker")
                        .WithMany("PreMatchOdds")
                        .HasForeignKey("BookmakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.Fixture", "Fixture")
                        .WithMany("PreMatchOdds")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bookmaker");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SmartBets.Entities.Standing", b =>
                {
                    b.HasOne("SmartBets.Entities.League", "League")
                        .WithMany("Standings")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.Team", "Team")
                        .WithMany("Standings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SmartBets.Entities.Team", b =>
                {
                    b.HasOne("SmartBets.Entities.Country", "Country")
                        .WithMany("Teams")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SmartBets.Entities.Bookmaker", b =>
                {
                    b.Navigation("PreMatchOdds");
                });

            modelBuilder.Entity("SmartBets.Entities.Country", b =>
                {
                    b.Navigation("Leagues");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SmartBets.Entities.Fixture", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Lineups");

                    b.Navigation("PlayerStatistics");

                    b.Navigation("PreMatchOdds");

                    b.Navigation("Statistics");
                });

            modelBuilder.Entity("SmartBets.Entities.League", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("SmartBets.Entities.Team", b =>
                {
                    b.Navigation("Standings");
                });
#pragma warning restore 612, 618
        }
    }
}
