// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartBets.Data;

#nullable disable

namespace SmartBets.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331135311_Stage1CoverageAndSyncErrors")]
    partial class Stage1CoverageAndSyncErrors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartBets.Entities.Bookmaker", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiBookmakerId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_bookmaker_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ApiBookmakerId")
                        .IsUnique();

                    b.ToTable("bookmakers", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<string>("FlagUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("flag_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.ToTable("countries", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Fixture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiFixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_fixture_id");

                    b.Property<int?>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<long>("AwayTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("away_team_id");

                    b.Property<int?>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<long>("HomeTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("home_team_id");

                    b.Property<DateTime>("KickoffAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kickoff_at");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_id");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ApiFixtureId")
                        .IsUnique();

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("KickoffAt");

                    b.HasIndex("LeagueId");

                    b.ToTable("fixtures", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.League", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiLeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_league_id");

                    b.Property<long>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ApiLeagueId", "Season")
                        .IsUnique();

                    b.ToTable("leagues", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.LeagueSeasonCoverage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("HasFixtureEvents")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fixture_events");

                    b.Property<bool>("HasFixtureStatistics")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fixture_statistics");

                    b.Property<bool>("HasFixtures")
                        .HasColumnType("boolean")
                        .HasColumnName("has_fixtures");

                    b.Property<bool>("HasInjuries")
                        .HasColumnType("boolean")
                        .HasColumnName("has_injuries");

                    b.Property<bool>("HasLineups")
                        .HasColumnType("boolean")
                        .HasColumnName("has_lineups");

                    b.Property<bool>("HasOdds")
                        .HasColumnType("boolean")
                        .HasColumnName("has_odds");

                    b.Property<bool>("HasPlayerStatistics")
                        .HasColumnType("boolean")
                        .HasColumnName("has_player_statistics");

                    b.Property<bool>("HasPlayers")
                        .HasColumnType("boolean")
                        .HasColumnName("has_players");

                    b.Property<bool>("HasPredictions")
                        .HasColumnType("boolean")
                        .HasColumnName("has_predictions");

                    b.Property<bool>("HasStandings")
                        .HasColumnType("boolean")
                        .HasColumnName("has_standings");

                    b.Property<bool>("HasTopAssists")
                        .HasColumnType("boolean")
                        .HasColumnName("has_top_assists");

                    b.Property<bool>("HasTopCards")
                        .HasColumnType("boolean")
                        .HasColumnName("has_top_cards");

                    b.Property<bool>("HasTopScorers")
                        .HasColumnType("boolean")
                        .HasColumnName("has_top_scorers");

                    b.Property<long>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Season");

                    b.HasIndex("LeagueApiId", "Season")
                        .IsUnique();

                    b.ToTable("league_season_coverages", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.PreMatchOdd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AwayOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("away_odd");

                    b.Property<long>("BookmakerId")
                        .HasColumnType("bigint")
                        .HasColumnName("bookmaker_id");

                    b.Property<DateTime>("CollectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("collected_at");

                    b.Property<decimal?>("DrawOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("draw_odd");

                    b.Property<long>("FixtureId")
                        .HasColumnType("bigint")
                        .HasColumnName("fixture_id");

                    b.Property<decimal?>("HomeOdd")
                        .HasColumnType("numeric")
                        .HasColumnName("home_odd");

                    b.Property<string>("MarketName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("market_name");

                    b.HasKey("Id");

                    b.HasIndex("BookmakerId");

                    b.HasIndex("FixtureId");

                    b.HasIndex("FixtureId", "BookmakerId", "MarketName", "CollectedAt");

                    b.ToTable("pre_match_odds", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Standing", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<int>("Draw")
                        .HasColumnType("integer")
                        .HasColumnName("draw");

                    b.Property<string>("Form")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("form");

                    b.Property<int>("GoalsAgainst")
                        .HasColumnType("integer")
                        .HasColumnName("goals_against");

                    b.Property<int>("GoalsDiff")
                        .HasColumnType("integer")
                        .HasColumnName("goals_diff");

                    b.Property<int>("GoalsFor")
                        .HasColumnType("integer")
                        .HasColumnName("goals_for");

                    b.Property<string>("GroupName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<long>("LeagueId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_id");

                    b.Property<int>("Lose")
                        .HasColumnType("integer")
                        .HasColumnName("lose");

                    b.Property<int>("Played")
                        .HasColumnType("integer")
                        .HasColumnName("played");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<long>("TeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("team_id");

                    b.Property<int>("Win")
                        .HasColumnType("integer")
                        .HasColumnName("win");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.HasIndex("Rank");

                    b.HasIndex("TeamId");

                    b.HasIndex("LeagueId", "Season", "TeamId")
                        .IsUnique();

                    b.ToTable("standings", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.SupportedLeague", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<long>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<int>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.HasIndex("LeagueApiId", "Season")
                        .IsUnique();

                    b.ToTable("supported_leagues", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.SyncError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error_message");

                    b.Property<long?>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<int?>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("EntityType");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("EntityType", "LeagueApiId", "Season");

                    b.ToTable("sync_errors", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.SyncState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("entity_type");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<long?>("LeagueApiId")
                        .HasColumnType("bigint")
                        .HasColumnName("league_api_id");

                    b.Property<int?>("Season")
                        .HasColumnType("integer")
                        .HasColumnName("season");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "LeagueApiId", "Season")
                        .IsUnique();

                    b.ToTable("sync_states", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Team", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ApiTeamId")
                        .HasColumnType("bigint")
                        .HasColumnName("api_team_id");

                    b.Property<string>("Code")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<long?>("CountryId")
                        .HasColumnType("bigint")
                        .HasColumnName("country_id");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("ApiTeamId")
                        .IsUnique();

                    b.HasIndex("CountryId");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("SmartBets.Entities.Fixture", b =>
                {
                    b.HasOne("SmartBets.Entities.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.League", "League")
                        .WithMany("Fixtures")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("SmartBets.Entities.League", b =>
                {
                    b.HasOne("SmartBets.Entities.Country", "Country")
                        .WithMany("Leagues")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SmartBets.Entities.PreMatchOdd", b =>
                {
                    b.HasOne("SmartBets.Entities.Bookmaker", "Bookmaker")
                        .WithMany("PreMatchOdds")
                        .HasForeignKey("BookmakerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.Fixture", "Fixture")
                        .WithMany("PreMatchOdds")
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bookmaker");

                    b.Navigation("Fixture");
                });

            modelBuilder.Entity("SmartBets.Entities.Standing", b =>
                {
                    b.HasOne("SmartBets.Entities.League", "League")
                        .WithMany("Standings")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartBets.Entities.Team", "Team")
                        .WithMany("Standings")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("League");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("SmartBets.Entities.Team", b =>
                {
                    b.HasOne("SmartBets.Entities.Country", "Country")
                        .WithMany("Teams")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SmartBets.Entities.Bookmaker", b =>
                {
                    b.Navigation("PreMatchOdds");
                });

            modelBuilder.Entity("SmartBets.Entities.Country", b =>
                {
                    b.Navigation("Leagues");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("SmartBets.Entities.Fixture", b =>
                {
                    b.Navigation("PreMatchOdds");
                });

            modelBuilder.Entity("SmartBets.Entities.League", b =>
                {
                    b.Navigation("Fixtures");

                    b.Navigation("Standings");
                });

            modelBuilder.Entity("SmartBets.Entities.Team", b =>
                {
                    b.Navigation("Standings");
                });
#pragma warning restore 612, 618
        }
    }
}
