ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_event_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_lineups_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_player_statistics_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_statistics_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS post_finish_match_center_sync_count integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS fixture_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    sort_order integer NOT NULL,
    elapsed integer NULL,
    extra integer NULL,
    team_id bigint NULL,
    api_team_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    player_api_id bigint NULL,
    player_name character varying(200) NULL,
    assist_api_id bigint NULL,
    assist_name character varying(200) NULL,
    type character varying(100) NOT NULL,
    detail character varying(200) NULL,
    comments character varying(500) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_events_fixture_id
    ON fixture_events (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_events_fixture_id_sort_order
    ON fixture_events (fixture_id, sort_order);

CREATE TABLE IF NOT EXISTS fixture_lineups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NOT NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    formation character varying(50) NULL,
    coach_api_id bigint NULL,
    coach_name character varying(200) NULL,
    coach_photo_url character varying(500) NULL,
    is_starting boolean NOT NULL,
    sort_order integer NOT NULL,
    player_api_id bigint NULL,
    player_name character varying(200) NOT NULL,
    player_number integer NULL,
    player_position character varying(20) NULL,
    player_grid character varying(50) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_lineups_fixture_id
    ON fixture_lineups (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_lineups_fixture_id_api_team_id_is_starting_sort_order
    ON fixture_lineups (fixture_id, api_team_id, is_starting, sort_order);

CREATE TABLE IF NOT EXISTS fixture_statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NOT NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    sort_order integer NOT NULL,
    type character varying(100) NOT NULL,
    value character varying(100) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_statistics_fixture_id
    ON fixture_statistics (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_statistics_fixture_id_api_team_id_sort_order
    ON fixture_statistics (fixture_id, api_team_id, sort_order);

CREATE TABLE IF NOT EXISTS fixture_player_statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NOT NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    sort_order integer NOT NULL,
    player_api_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    minutes integer NULL,
    number integer NULL,
    position character varying(20) NULL,
    rating numeric(6,2) NULL,
    is_captain boolean NOT NULL DEFAULT FALSE,
    is_substitute boolean NOT NULL DEFAULT FALSE,
    offsides integer NULL,
    shots_total integer NULL,
    shots_on integer NULL,
    goals_total integer NULL,
    goals_conceded integer NULL,
    goals_assists integer NULL,
    goals_saves integer NULL,
    passes_total integer NULL,
    passes_key integer NULL,
    passes_accuracy character varying(20) NULL,
    tackles_total integer NULL,
    tackles_blocks integer NULL,
    tackles_interceptions integer NULL,
    duels_total integer NULL,
    duels_won integer NULL,
    dribbles_attempts integer NULL,
    dribbles_success integer NULL,
    dribbles_past integer NULL,
    fouls_drawn integer NULL,
    fouls_committed integer NULL,
    cards_yellow integer NULL,
    cards_red integer NULL,
    penalty_won integer NULL,
    penalty_committed integer NULL,
    penalty_scored integer NULL,
    penalty_missed integer NULL,
    penalty_saved integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_player_statistics_fixture_id
    ON fixture_player_statistics (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_player_statistics_fixture_id_api_team_id_player_api_id
    ON fixture_player_statistics (fixture_id, api_team_id, player_api_id);

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_prediction_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_injuries_synced_at_utc timestamp with time zone NULL;

CREATE TABLE IF NOT EXISTS fixture_predictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    winner_team_api_id bigint NULL,
    winner_team_name character varying(200) NULL,
    winner_comment character varying(500) NULL,
    win_or_draw boolean NULL,
    under_over character varying(50) NULL,
    advice character varying(500) NULL,
    goals_home character varying(50) NULL,
    goals_away character varying(50) NULL,
    percent_home character varying(50) NULL,
    percent_draw character varying(50) NULL,
    percent_away character varying(50) NULL,
    comparison_form_home character varying(50) NULL,
    comparison_form_away character varying(50) NULL,
    comparison_attack_home character varying(50) NULL,
    comparison_attack_away character varying(50) NULL,
    comparison_defence_home character varying(50) NULL,
    comparison_defence_away character varying(50) NULL,
    comparison_poisson_home character varying(50) NULL,
    comparison_poisson_away character varying(50) NULL,
    comparison_head_to_head_home character varying(50) NULL,
    comparison_head_to_head_away character varying(50) NULL,
    comparison_goals_home character varying(50) NULL,
    comparison_goals_away character varying(50) NULL,
    comparison_total_home character varying(50) NULL,
    comparison_total_away character varying(50) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_predictions_fixture_id
    ON fixture_predictions (fixture_id);

CREATE TABLE IF NOT EXISTS fixture_injuries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    player_api_id bigint NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    type character varying(100) NULL,
    reason character varying(500) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_injuries_fixture_id
    ON fixture_injuries (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_injuries_fixture_id_api_team_id
    ON fixture_injuries (fixture_id, api_team_id);

CREATE TABLE IF NOT EXISTS team_statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    form character varying(50) NOT NULL,
    fixtures_played_total integer NOT NULL,
    fixtures_played_home integer NOT NULL,
    fixtures_played_away integer NOT NULL,
    wins_total integer NOT NULL,
    wins_home integer NOT NULL,
    wins_away integer NOT NULL,
    draws_total integer NOT NULL,
    draws_home integer NOT NULL,
    draws_away integer NOT NULL,
    losses_total integer NOT NULL,
    losses_home integer NOT NULL,
    losses_away integer NOT NULL,
    goals_for_total integer NOT NULL,
    goals_for_home integer NOT NULL,
    goals_for_away integer NOT NULL,
    goals_for_average_total character varying(20) NULL,
    goals_for_average_home character varying(20) NULL,
    goals_for_average_away character varying(20) NULL,
    goals_against_total integer NOT NULL,
    goals_against_home integer NOT NULL,
    goals_against_away integer NOT NULL,
    goals_against_average_total character varying(20) NULL,
    goals_against_average_home character varying(20) NULL,
    goals_against_average_away character varying(20) NULL,
    clean_sheets_total integer NOT NULL,
    clean_sheets_home integer NOT NULL,
    clean_sheets_away integer NOT NULL,
    failed_to_score_total integer NOT NULL,
    failed_to_score_home integer NOT NULL,
    failed_to_score_away integer NOT NULL,
    biggest_streak_wins integer NOT NULL,
    biggest_streak_draws integer NOT NULL,
    biggest_streak_losses integer NOT NULL,
    biggest_win_home character varying(20) NULL,
    biggest_win_away character varying(20) NULL,
    biggest_loss_home character varying(20) NULL,
    biggest_loss_away character varying(20) NULL,
    biggest_goals_for_home integer NULL,
    biggest_goals_for_away integer NULL,
    biggest_goals_against_home integer NULL,
    biggest_goals_against_away integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_team_statistics_team_id_league_id_season
    ON team_statistics (team_id, league_id, season);

CREATE INDEX IF NOT EXISTS ix_team_statistics_team_id
    ON team_statistics (team_id);

CREATE INDEX IF NOT EXISTS ix_team_statistics_league_id
    ON team_statistics (league_id);

CREATE TABLE IF NOT EXISTS league_rounds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    round_name character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    is_current boolean NOT NULL DEFAULT FALSE,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_rounds_league_id_season_round_name
    ON league_rounds (league_id, season, round_name);

CREATE INDEX IF NOT EXISTS ix_league_rounds_league_id_season_sort_order
    ON league_rounds (league_id, season, sort_order);

CREATE TABLE IF NOT EXISTS league_top_scorers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    rank integer NOT NULL,
    api_player_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    team_id bigint NULL,
    team_api_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    appearances integer NULL,
    minutes integer NULL,
    position character varying(50) NULL,
    rating numeric(6,2) NULL,
    goals integer NULL,
    assists integer NULL,
    shots_total integer NULL,
    shots_on integer NULL,
    penalties_scored integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_top_scorers_league_id_season_rank
    ON league_top_scorers (league_id, season, rank);

CREATE INDEX IF NOT EXISTS ix_league_top_scorers_league_id_season_api_player_id
    ON league_top_scorers (league_id, season, api_player_id);

CREATE TABLE IF NOT EXISTS league_top_assists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    rank integer NOT NULL,
    api_player_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    team_id bigint NULL,
    team_api_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    appearances integer NULL,
    minutes integer NULL,
    position character varying(50) NULL,
    rating numeric(6,2) NULL,
    goals integer NULL,
    assists integer NULL,
    passes_key integer NULL,
    chances_created integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_top_assists_league_id_season_rank
    ON league_top_assists (league_id, season, rank);

CREATE INDEX IF NOT EXISTS ix_league_top_assists_league_id_season_api_player_id
    ON league_top_assists (league_id, season, api_player_id);

CREATE TABLE IF NOT EXISTS league_top_cards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    combined_rank integer NOT NULL,
    yellow_rank integer NULL,
    red_rank integer NULL,
    api_player_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    team_id bigint NULL,
    team_api_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    appearances integer NULL,
    minutes integer NULL,
    position character varying(50) NULL,
    rating numeric(6,2) NULL,
    yellow_cards integer NOT NULL DEFAULT 0,
    red_cards integer NOT NULL DEFAULT 0,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_top_cards_league_id_season_combined_rank
    ON league_top_cards (league_id, season, combined_rank);

CREATE INDEX IF NOT EXISTS ix_league_top_cards_league_id_season_api_player_id
    ON league_top_cards (league_id, season, api_player_id);

CREATE TABLE IF NOT EXISTS odds_open_close (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    bookmaker_id bigint NOT NULL REFERENCES bookmakers(id) ON DELETE RESTRICT,
    market_name character varying(100) NOT NULL,
    snapshot_count integer NOT NULL,
    opening_home_odd numeric NULL,
    opening_draw_odd numeric NULL,
    opening_away_odd numeric NULL,
    opening_collected_at_utc timestamp with time zone NULL,
    latest_home_odd numeric NULL,
    latest_draw_odd numeric NULL,
    latest_away_odd numeric NULL,
    latest_collected_at_utc timestamp with time zone NULL,
    peak_home_odd numeric NULL,
    peak_draw_odd numeric NULL,
    peak_away_odd numeric NULL,
    peak_home_collected_at_utc timestamp with time zone NULL,
    peak_draw_collected_at_utc timestamp with time zone NULL,
    peak_away_collected_at_utc timestamp with time zone NULL,
    closing_home_odd numeric NULL,
    closing_draw_odd numeric NULL,
    closing_away_odd numeric NULL,
    closing_collected_at_utc timestamp with time zone NULL,
    updated_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_odds_open_close_fixture_id_bookmaker_id_market_name
    ON odds_open_close (fixture_id, bookmaker_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_open_close_fixture_id_market_name
    ON odds_open_close (fixture_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_open_close_bookmaker_id
    ON odds_open_close (bookmaker_id);

CREATE TABLE IF NOT EXISTS odds_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    bookmaker_id bigint NOT NULL REFERENCES bookmakers(id) ON DELETE RESTRICT,
    market_name character varying(100) NOT NULL,
    snapshot_count integer NOT NULL,
    first_collected_at_utc timestamp with time zone NULL,
    last_collected_at_utc timestamp with time zone NULL,
    home_delta numeric NULL,
    draw_delta numeric NULL,
    away_delta numeric NULL,
    home_change_percent numeric NULL,
    draw_change_percent numeric NULL,
    away_change_percent numeric NULL,
    home_swing numeric NULL,
    draw_swing numeric NULL,
    away_swing numeric NULL,
    updated_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_odds_movements_fixture_id_bookmaker_id_market_name
    ON odds_movements (fixture_id, bookmaker_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_movements_fixture_id_market_name
    ON odds_movements (fixture_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_movements_bookmaker_id
    ON odds_movements (bookmaker_id);

CREATE TABLE IF NOT EXISTS market_consensus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    market_name character varying(100) NOT NULL,
    sample_size integer NOT NULL,
    opening_home_consensus_odd numeric NULL,
    opening_draw_consensus_odd numeric NULL,
    opening_away_consensus_odd numeric NULL,
    latest_home_consensus_odd numeric NULL,
    latest_draw_consensus_odd numeric NULL,
    latest_away_consensus_odd numeric NULL,
    best_home_odd numeric NULL,
    best_draw_odd numeric NULL,
    best_away_odd numeric NULL,
    best_home_bookmaker_id bigint NULL,
    best_draw_bookmaker_id bigint NULL,
    best_away_bookmaker_id bigint NULL,
    max_home_spread numeric NULL,
    max_draw_spread numeric NULL,
    max_away_spread numeric NULL,
    updated_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_market_consensus_fixture_id_market_name
    ON market_consensus (fixture_id, market_name);
