CREATE TABLE IF NOT EXISTS odds_open_close (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    bookmaker_id bigint NOT NULL REFERENCES bookmakers(id) ON DELETE RESTRICT,
    market_name character varying(100) NOT NULL,
    snapshot_count integer NOT NULL,
    opening_home_odd numeric NULL,
    opening_draw_odd numeric NULL,
    opening_away_odd numeric NULL,
    opening_collected_at_utc timestamp with time zone NULL,
    latest_home_odd numeric NULL,
    latest_draw_odd numeric NULL,
    latest_away_odd numeric NULL,
    latest_collected_at_utc timestamp with time zone NULL,
    peak_home_odd numeric NULL,
    peak_draw_odd numeric NULL,
    peak_away_odd numeric NULL,
    peak_home_collected_at_utc timestamp with time zone NULL,
    peak_draw_collected_at_utc timestamp with time zone NULL,
    peak_away_collected_at_utc timestamp with time zone NULL,
    closing_home_odd numeric NULL,
    closing_draw_odd numeric NULL,
    closing_away_odd numeric NULL,
    closing_collected_at_utc timestamp with time zone NULL,
    updated_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_odds_open_close_fixture_id_bookmaker_id_market_name
    ON odds_open_close (fixture_id, bookmaker_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_open_close_fixture_id_market_name
    ON odds_open_close (fixture_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_open_close_bookmaker_id
    ON odds_open_close (bookmaker_id);

CREATE TABLE IF NOT EXISTS odds_movements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    bookmaker_id bigint NOT NULL REFERENCES bookmakers(id) ON DELETE RESTRICT,
    market_name character varying(100) NOT NULL,
    snapshot_count integer NOT NULL,
    first_collected_at_utc timestamp with time zone NULL,
    last_collected_at_utc timestamp with time zone NULL,
    home_delta numeric NULL,
    draw_delta numeric NULL,
    away_delta numeric NULL,
    home_change_percent numeric NULL,
    draw_change_percent numeric NULL,
    away_change_percent numeric NULL,
    home_swing numeric NULL,
    draw_swing numeric NULL,
    away_swing numeric NULL,
    updated_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_odds_movements_fixture_id_bookmaker_id_market_name
    ON odds_movements (fixture_id, bookmaker_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_movements_fixture_id_market_name
    ON odds_movements (fixture_id, market_name);

CREATE INDEX IF NOT EXISTS ix_odds_movements_bookmaker_id
    ON odds_movements (bookmaker_id);

CREATE TABLE IF NOT EXISTS market_consensus (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    market_name character varying(100) NOT NULL,
    sample_size integer NOT NULL,
    opening_home_consensus_odd numeric NULL,
    opening_draw_consensus_odd numeric NULL,
    opening_away_consensus_odd numeric NULL,
    latest_home_consensus_odd numeric NULL,
    latest_draw_consensus_odd numeric NULL,
    latest_away_consensus_odd numeric NULL,
    best_home_odd numeric NULL,
    best_draw_odd numeric NULL,
    best_away_odd numeric NULL,
    best_home_bookmaker_id bigint NULL,
    best_draw_bookmaker_id bigint NULL,
    best_away_bookmaker_id bigint NULL,
    max_home_spread numeric NULL,
    max_draw_spread numeric NULL,
    max_away_spread numeric NULL,
    updated_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_market_consensus_fixture_id_market_name
    ON market_consensus (fixture_id, market_name);
