START TRANSACTION;

CREATE TABLE the_odds_runtime_settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    setting_key character varying(100) NOT NULL,
    bool_value boolean NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    updated_by character varying(200) NULL,
    CONSTRAINT "PK_the_odds_runtime_settings" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_the_odds_runtime_settings_setting_key"
    ON the_odds_runtime_settings (setting_key);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260411115043_Stage13TheOddsViewerRefreshState', '8.0.8');

COMMIT;
