CREATE TABLE IF NOT EXISTS league_season_coverages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_api_id bigint NOT NULL,
    season integer NOT NULL,
    has_fixtures boolean NOT NULL DEFAULT FALSE,
    has_fixture_events boolean NOT NULL DEFAULT FALSE,
    has_lineups boolean NOT NULL DEFAULT FALSE,
    has_fixture_statistics boolean NOT NULL DEFAULT FALSE,
    has_player_statistics boolean NOT NULL DEFAULT FALSE,
    has_standings boolean NOT NULL DEFAULT FALSE,
    has_players boolean NOT NULL DEFAULT FALSE,
    has_top_scorers boolean NOT NULL DEFAULT FALSE,
    has_top_assists boolean NOT NULL DEFAULT FALSE,
    has_top_cards boolean NOT NULL DEFAULT FALSE,
    has_injuries boolean NOT NULL DEFAULT FALSE,
    has_predictions boolean NOT NULL DEFAULT FALSE,
    has_odds boolean NOT NULL DEFAULT FALSE,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_season_coverages_league_api_id_season
    ON league_season_coverages (league_api_id, season);

CREATE INDEX IF NOT EXISTS ix_league_season_coverages_season
    ON league_season_coverages (season);

CREATE TABLE IF NOT EXISTS sync_errors (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type character varying(50) NOT NULL,
    operation character varying(100) NOT NULL,
    league_api_id bigint NULL,
    season integer NULL,
    source character varying(50) NOT NULL,
    error_message character varying(2000) NOT NULL,
    occurred_at timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_sync_errors_entity_type
    ON sync_errors (entity_type);

CREATE INDEX IF NOT EXISTS ix_sync_errors_entity_type_league_api_id_season
    ON sync_errors (entity_type, league_api_id, season);

CREATE INDEX IF NOT EXISTS ix_sync_errors_occurred_at
    ON sync_errors (occurred_at);
