ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_event_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_lineups_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_player_statistics_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_statistics_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS post_finish_match_center_sync_count integer NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS fixture_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    sort_order integer NOT NULL,
    elapsed integer NULL,
    extra integer NULL,
    team_id bigint NULL,
    api_team_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    player_api_id bigint NULL,
    player_name character varying(200) NULL,
    assist_api_id bigint NULL,
    assist_name character varying(200) NULL,
    type character varying(100) NOT NULL,
    detail character varying(200) NULL,
    comments character varying(500) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_events_fixture_id
    ON fixture_events (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_events_fixture_id_sort_order
    ON fixture_events (fixture_id, sort_order);

CREATE TABLE IF NOT EXISTS fixture_lineups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NOT NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    formation character varying(50) NULL,
    coach_api_id bigint NULL,
    coach_name character varying(200) NULL,
    coach_photo_url character varying(500) NULL,
    is_starting boolean NOT NULL,
    sort_order integer NOT NULL,
    player_api_id bigint NULL,
    player_name character varying(200) NOT NULL,
    player_number integer NULL,
    player_position character varying(20) NULL,
    player_grid character varying(50) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_lineups_fixture_id
    ON fixture_lineups (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_lineups_fixture_id_api_team_id_is_starting_sort_order
    ON fixture_lineups (fixture_id, api_team_id, is_starting, sort_order);

CREATE TABLE IF NOT EXISTS fixture_statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NOT NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    sort_order integer NOT NULL,
    type character varying(100) NOT NULL,
    value character varying(100) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_statistics_fixture_id
    ON fixture_statistics (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_statistics_fixture_id_api_team_id_sort_order
    ON fixture_statistics (fixture_id, api_team_id, sort_order);

CREATE TABLE IF NOT EXISTS fixture_player_statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NOT NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    sort_order integer NOT NULL,
    player_api_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    minutes integer NULL,
    number integer NULL,
    position character varying(20) NULL,
    rating numeric(6,2) NULL,
    is_captain boolean NOT NULL DEFAULT FALSE,
    is_substitute boolean NOT NULL DEFAULT FALSE,
    offsides integer NULL,
    shots_total integer NULL,
    shots_on integer NULL,
    goals_total integer NULL,
    goals_conceded integer NULL,
    goals_assists integer NULL,
    goals_saves integer NULL,
    passes_total integer NULL,
    passes_key integer NULL,
    passes_accuracy character varying(20) NULL,
    tackles_total integer NULL,
    tackles_blocks integer NULL,
    tackles_interceptions integer NULL,
    duels_total integer NULL,
    duels_won integer NULL,
    dribbles_attempts integer NULL,
    dribbles_success integer NULL,
    dribbles_past integer NULL,
    fouls_drawn integer NULL,
    fouls_committed integer NULL,
    cards_yellow integer NULL,
    cards_red integer NULL,
    penalty_won integer NULL,
    penalty_committed integer NULL,
    penalty_scored integer NULL,
    penalty_missed integer NULL,
    penalty_saved integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_player_statistics_fixture_id
    ON fixture_player_statistics (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_player_statistics_fixture_id_api_team_id_player_api_id
    ON fixture_player_statistics (fixture_id, api_team_id, player_api_id);
