ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_prediction_synced_at_utc timestamp with time zone NULL;

ALTER TABLE fixtures
    ADD COLUMN IF NOT EXISTS last_injuries_synced_at_utc timestamp with time zone NULL;

CREATE TABLE IF NOT EXISTS fixture_predictions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    winner_team_api_id bigint NULL,
    winner_team_name character varying(200) NULL,
    winner_comment character varying(500) NULL,
    win_or_draw boolean NULL,
    under_over character varying(50) NULL,
    advice character varying(500) NULL,
    goals_home character varying(50) NULL,
    goals_away character varying(50) NULL,
    percent_home character varying(50) NULL,
    percent_draw character varying(50) NULL,
    percent_away character varying(50) NULL,
    comparison_form_home character varying(50) NULL,
    comparison_form_away character varying(50) NULL,
    comparison_attack_home character varying(50) NULL,
    comparison_attack_away character varying(50) NULL,
    comparison_defence_home character varying(50) NULL,
    comparison_defence_away character varying(50) NULL,
    comparison_poisson_home character varying(50) NULL,
    comparison_poisson_away character varying(50) NULL,
    comparison_head_to_head_home character varying(50) NULL,
    comparison_head_to_head_away character varying(50) NULL,
    comparison_goals_home character varying(50) NULL,
    comparison_goals_away character varying(50) NULL,
    comparison_total_home character varying(50) NULL,
    comparison_total_away character varying(50) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_predictions_fixture_id
    ON fixture_predictions (fixture_id);

CREATE TABLE IF NOT EXISTS fixture_injuries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    team_id bigint NULL,
    api_team_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    player_api_id bigint NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    type character varying(100) NULL,
    reason character varying(500) NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_fixture_injuries_fixture_id
    ON fixture_injuries (fixture_id);

CREATE INDEX IF NOT EXISTS ix_fixture_injuries_fixture_id_api_team_id
    ON fixture_injuries (fixture_id, api_team_id);
