CREATE TABLE IF NOT EXISTS content_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_key VARCHAR(100) NOT NULL,
    payload_json TEXT NOT NULL,
    created_at_utc TIMESTAMPTZ NOT NULL,
    updated_at_utc TIMESTAMPTZ NOT NULL,
    updated_by VARCHAR(200) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_content_documents_content_key
    ON content_documents (content_key);
