START TRANSACTION;

CREATE TABLE the_odds_league_mappings (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    api_football_league_id bigint NOT NULL,
    league_name character varying(200) NOT NULL,
    country_name character varying(200) NOT NULL,
    the_odds_sport_key character varying(100),
    resolution_source character varying(50) NOT NULL,
    confidence integer NOT NULL,
    is_verified boolean NOT NULL,
    notes character varying(500),
    created_at_utc timestamp with time zone NOT NULL,
    updated_at_utc timestamp with time zone NOT NULL,
    last_resolved_at_utc timestamp with time zone,
    last_used_at_utc timestamp with time zone,
    CONSTRAINT "PK_the_odds_league_mappings" PRIMARY KEY (id)
);

CREATE UNIQUE INDEX "IX_the_odds_league_mappings_api_football_league_id"
    ON the_odds_league_mappings (api_football_league_id);

CREATE INDEX "IX_the_odds_league_mappings_resolution_source"
    ON the_odds_league_mappings (resolution_source);

CREATE INDEX "IX_the_odds_league_mappings_the_odds_sport_key"
    ON the_odds_league_mappings (the_odds_sport_key);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260410183907_Stage12TheOddsLeagueMappings', '8.0.8');

COMMIT;
