START TRANSACTION;

CREATE TABLE live_bet_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    api_bet_id bigint NOT NULL,
    name character varying(200) NOT NULL,
    synced_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_live_bet_types" PRIMARY KEY (id),
    CONSTRAINT "AK_live_bet_types_api_bet_id" UNIQUE (api_bet_id)
);

CREATE TABLE live_odds (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fixture_id bigint NOT NULL,
    bookmaker_id bigint NOT NULL,
    api_bet_id bigint NOT NULL,
    bet_name character varying(200) NOT NULL,
    outcome_label character varying(200) NOT NULL,
    line character varying(100),
    odd numeric,
    is_main boolean,
    stopped boolean,
    blocked boolean,
    finished boolean,
    collected_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_live_odds" PRIMARY KEY (id),
    CONSTRAINT "FK_live_odds_bookmakers_bookmaker_id" FOREIGN KEY (bookmaker_id) REFERENCES bookmakers (id) ON DELETE RESTRICT,
    CONSTRAINT "FK_live_odds_fixtures_fixture_id" FOREIGN KEY (fixture_id) REFERENCES fixtures (id) ON DELETE CASCADE,
    CONSTRAINT "FK_live_odds_live_bet_types_api_bet_id" FOREIGN KEY (api_bet_id) REFERENCES live_bet_types (api_bet_id) ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_live_bet_types_api_bet_id" ON live_bet_types (api_bet_id);

CREATE INDEX "IX_live_odds_api_bet_id" ON live_odds (api_bet_id);

CREATE INDEX "IX_live_odds_bookmaker_id" ON live_odds (bookmaker_id);

CREATE INDEX "IX_live_odds_fixture_id" ON live_odds (fixture_id);

CREATE INDEX "IX_live_odds_fixture_id_bookmaker_id_api_bet_id_outcome_label_~" ON live_odds (fixture_id, bookmaker_id, api_bet_id, outcome_label, line, collected_at_utc);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260331190852_Stage7LiveOddsAndFixtureBatchSync', '8.0.8');

COMMIT;

