CREATE TABLE IF NOT EXISTS team_statistics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    team_id bigint NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    form character varying(50) NOT NULL,
    fixtures_played_total integer NOT NULL,
    fixtures_played_home integer NOT NULL,
    fixtures_played_away integer NOT NULL,
    wins_total integer NOT NULL,
    wins_home integer NOT NULL,
    wins_away integer NOT NULL,
    draws_total integer NOT NULL,
    draws_home integer NOT NULL,
    draws_away integer NOT NULL,
    losses_total integer NOT NULL,
    losses_home integer NOT NULL,
    losses_away integer NOT NULL,
    goals_for_total integer NOT NULL,
    goals_for_home integer NOT NULL,
    goals_for_away integer NOT NULL,
    goals_for_average_total character varying(20) NULL,
    goals_for_average_home character varying(20) NULL,
    goals_for_average_away character varying(20) NULL,
    goals_against_total integer NOT NULL,
    goals_against_home integer NOT NULL,
    goals_against_away integer NOT NULL,
    goals_against_average_total character varying(20) NULL,
    goals_against_average_home character varying(20) NULL,
    goals_against_average_away character varying(20) NULL,
    clean_sheets_total integer NOT NULL,
    clean_sheets_home integer NOT NULL,
    clean_sheets_away integer NOT NULL,
    failed_to_score_total integer NOT NULL,
    failed_to_score_home integer NOT NULL,
    failed_to_score_away integer NOT NULL,
    biggest_streak_wins integer NOT NULL,
    biggest_streak_draws integer NOT NULL,
    biggest_streak_losses integer NOT NULL,
    biggest_win_home character varying(20) NULL,
    biggest_win_away character varying(20) NULL,
    biggest_loss_home character varying(20) NULL,
    biggest_loss_away character varying(20) NULL,
    biggest_goals_for_home integer NULL,
    biggest_goals_for_away integer NULL,
    biggest_goals_against_home integer NULL,
    biggest_goals_against_away integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_team_statistics_team_id_league_id_season
    ON team_statistics (team_id, league_id, season);

CREATE INDEX IF NOT EXISTS ix_team_statistics_team_id
    ON team_statistics (team_id);

CREATE INDEX IF NOT EXISTS ix_team_statistics_league_id
    ON team_statistics (league_id);

CREATE TABLE IF NOT EXISTS league_rounds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    round_name character varying(200) NOT NULL,
    sort_order integer NOT NULL,
    is_current boolean NOT NULL DEFAULT FALSE,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_rounds_league_id_season_round_name
    ON league_rounds (league_id, season, round_name);

CREATE INDEX IF NOT EXISTS ix_league_rounds_league_id_season_sort_order
    ON league_rounds (league_id, season, sort_order);

CREATE TABLE IF NOT EXISTS league_top_scorers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    rank integer NOT NULL,
    api_player_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    team_id bigint NULL,
    team_api_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    appearances integer NULL,
    minutes integer NULL,
    position character varying(50) NULL,
    rating numeric(6,2) NULL,
    goals integer NULL,
    assists integer NULL,
    shots_total integer NULL,
    shots_on integer NULL,
    penalties_scored integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_top_scorers_league_id_season_rank
    ON league_top_scorers (league_id, season, rank);

CREATE INDEX IF NOT EXISTS ix_league_top_scorers_league_id_season_api_player_id
    ON league_top_scorers (league_id, season, api_player_id);

CREATE TABLE IF NOT EXISTS league_top_assists (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    rank integer NOT NULL,
    api_player_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    team_id bigint NULL,
    team_api_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    appearances integer NULL,
    minutes integer NULL,
    position character varying(50) NULL,
    rating numeric(6,2) NULL,
    goals integer NULL,
    assists integer NULL,
    passes_key integer NULL,
    chances_created integer NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_top_assists_league_id_season_rank
    ON league_top_assists (league_id, season, rank);

CREATE INDEX IF NOT EXISTS ix_league_top_assists_league_id_season_api_player_id
    ON league_top_assists (league_id, season, api_player_id);

CREATE TABLE IF NOT EXISTS league_top_cards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    league_id bigint NOT NULL REFERENCES leagues(id) ON DELETE CASCADE,
    season integer NOT NULL,
    combined_rank integer NOT NULL,
    yellow_rank integer NULL,
    red_rank integer NULL,
    api_player_id bigint NOT NULL,
    player_name character varying(200) NOT NULL,
    player_photo_url character varying(500) NULL,
    team_id bigint NULL,
    team_api_id bigint NULL,
    team_name character varying(200) NOT NULL,
    team_logo_url character varying(500) NULL,
    appearances integer NULL,
    minutes integer NULL,
    position character varying(50) NULL,
    rating numeric(6,2) NULL,
    yellow_cards integer NOT NULL DEFAULT 0,
    red_cards integer NOT NULL DEFAULT 0,
    synced_at_utc timestamp with time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_league_top_cards_league_id_season_combined_rank
    ON league_top_cards (league_id, season, combined_rank);

CREATE INDEX IF NOT EXISTS ix_league_top_cards_league_id_season_api_player_id
    ON league_top_cards (league_id, season, api_player_id);
