START TRANSACTION;

CREATE TABLE the_odds_live_odds (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    fixture_id bigint NOT NULL,
    provider_event_id character varying(100) NOT NULL,
    sport_key character varying(100) NOT NULL,
    bookmaker_key character varying(100) NOT NULL,
    bookmaker_title character varying(200) NOT NULL,
    market_key character varying(100) NOT NULL,
    market_name character varying(100) NOT NULL,
    outcome_name character varying(200) NOT NULL,
    point numeric,
    price numeric,
    last_update_utc timestamp with time zone,
    collected_at_utc timestamp with time zone NOT NULL,
    CONSTRAINT "PK_the_odds_live_odds" PRIMARY KEY (id),
    CONSTRAINT "FK_the_odds_live_odds_fixtures_fixture_id" FOREIGN KEY (fixture_id) REFERENCES fixtures (id) ON DELETE CASCADE
);

CREATE INDEX "IX_the_odds_live_odds_collected_at_utc" ON the_odds_live_odds (collected_at_utc);

CREATE INDEX "IX_the_odds_live_odds_fixture_id" ON the_odds_live_odds (fixture_id);

CREATE INDEX "IX_the_odds_live_odds_fixture_id_bookmaker_key_market_key_coll~" ON the_odds_live_odds (fixture_id, bookmaker_key, market_key, collected_at_utc);

CREATE INDEX "IX_the_odds_live_odds_fixture_id_bookmaker_key_market_key_outc~" ON the_odds_live_odds (fixture_id, bookmaker_key, market_key, outcome_name, point, collected_at_utc);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260409191810_Stage11TheOddsApiLiveOdds', '8.0.8');

COMMIT;

