CREATE TABLE IF NOT EXISTS live_bet_types (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    api_bet_id bigint NOT NULL,
    name character varying(200) NOT NULL,
    synced_at_utc timestamp with time zone NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'AK_live_bet_types_api_bet_id'
          AND conrelid = 'live_bet_types'::regclass
    ) THEN
        ALTER TABLE live_bet_types
            ADD CONSTRAINT "AK_live_bet_types_api_bet_id" UNIQUE (api_bet_id);
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS live_odds (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fixture_id bigint NOT NULL REFERENCES fixtures(id) ON DELETE CASCADE,
    bookmaker_id bigint NOT NULL REFERENCES bookmakers(id) ON DELETE RESTRICT,
    api_bet_id bigint NOT NULL REFERENCES live_bet_types(api_bet_id) ON DELETE RESTRICT,
    bet_name character varying(200) NOT NULL,
    outcome_label character varying(200) NOT NULL,
    line character varying(100) NULL,
    odd numeric NULL,
    is_main boolean NULL,
    stopped boolean NULL,
    blocked boolean NULL,
    finished boolean NULL,
    collected_at_utc timestamp with time zone NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_live_odds_fixture_id
    ON live_odds (fixture_id);

CREATE INDEX IF NOT EXISTS ix_live_odds_bookmaker_id
    ON live_odds (bookmaker_id);

CREATE INDEX IF NOT EXISTS ix_live_odds_api_bet_id
    ON live_odds (api_bet_id);

CREATE INDEX IF NOT EXISTS ix_live_odds_snapshot_key
    ON live_odds (fixture_id, bookmaker_id, api_bet_id, outcome_label, line, collected_at_utc);
